### PR TITLE
Updating all dependencies and ng2 to 2.4

### PR DESCRIPTION
**Pull request by reblace**
This PR upgrades Angular to 2.4 and also upgrades a bunch of other dependencies to their latest versions. I had to make a few minor changes for the ng2-bootstrap upgrade.

Also, I added some imports that were missing from the vendor.js file (which makes the application.js file smaller [yay!] ).

Upgrading tslint led me to fixing some rules which have been changed/deprecated. I also moved the tslint config file to the root dir to match the eslint file and set it up so that it references the tslint recommended config with our specific overrides. There are some rules we should consider turning on and going through and cleaning up our code to match, but I'll leave that for another day.

We can keep this on a branch till the end of the month to minimize impact to the teams that are building off of the starter. We should also do more testing as I didn't test the Kafka integration (after upgrading that npm dep)

### CODE REVIEW

**Comment by brianghig** [comment]
@reblace the changes look good overall, though our fork is breaking on a few notes. If it helps the merge elsewhere, our main problems seem to be references to attributes by string literals (minor) and a few typing issues with params (e.g., `Property 'query' does not exist on type 'Params'` in reference to `Params` from `@angular/router`).

@bodnarbm I'm also seeing an error raised from the following snippet:
```
ngOnChanges(changes: SimpleChanges) {
	if (changes.initialSearch) {
		this.setFormQueryValue(this.initialSearch);
		this.setFormDateRange(this.initialSearch);
	}
}
```
`SimpleChanges` doesn't seem to have a non-property means of accessing the modified properties. Still looking into how we can handle this properly... It's in `search-bar.component.ts`.

**Comment by reblace** [comment]
We can allow access to attributes using string literals. SimpleChanges basically forces you to do it that way. We can chat tomorrow about the other issue. I don't want this branch merged yet anyways. We will do that next week likely (if you can wait). Though, I can using this branch on my Jira portal without issue.

**Comment by bodnarbm** [comment]
@reblace Yes. If we can add back disabling the tslint rule for no-string-indexers, that will solve the issue noted by @brianghig. We disabled it back in #47 as part of the implementing #46

**Comment by reblace** [comment]
I think this is ready to merge now

**Review by mheir — APPROVED** [review]

**Comment by ymao1** [comment]
Conflicts.

**Comment by ymao1** [comment]
I resolved the conflict but it looks like the changes to the mongoose.js file is causing a test to fail.

**Comment by bodnarbm** [comment]
Fixed the mongoose test. It was previously expecting the connecting to already be connected by the time the mongoose.connect() promise resolved. Now, the test handles the connections being in a connecting state, as long as the mongoose connection eventually connects within the test timeout window.

**Review by ymao1 — APPROVED** [review]

**Pull request merged**
