### PR TITLE
Add support for IE 9+

### PR DESCRIPTION
**Pull request by bodnarbm**
Adds basic support for IE9+.

Console.debug is not available in these browsers, so I replaced those lines with console.log. According to MDN, console.debug is simply an alias for console.log, but it looks like chrome does print them differently. We may want to consider changing those logs to a dedicated logger whose level we can specify per environment.

### CODE REVIEW

**Comment by reblace** [comment]
We should really add a logger sooner than later.

**Comment by bodnarbm** [comment]
@reblace Good point. Looks like there are only about ~20 references to console in the current code (references from client side). I can make the changes in this PR to add a logger, or I can do it as a separate PR. Preference?

**Comment by bodnarbm** [comment]
After discussions, I removed all the console statements from client side. We are going to separately add a new logging service to handle client side logging.

I also banned console.debug to prevent future errors with IE9 if we add back in console statements.

**Comment by reblace** [comment]
Love net negative PRs

**Pull request merged**
