### PR TITLE
[A-202] Adding utc date pipe

### PR DESCRIPTION
**Pull request by ymao1**
Adding date pipe to display dates in UTC. Added because the angular date pipe always displays dates in your local time zone.

### CODE REVIEW

**Review by mheir — APPROVED** [review]

**Comment by reblace** [comment]
Did we make a deliberate decision to not switch to using an third party package like https://github.com/urish/angular2-moment ?

**Comment by ymao1** [comment]
I looked into using angular2-moment (and we are using it on another project) but support for that library seemed a little spotty and it looks like it's only a single person developing it so I wasn't sure if it was a dependable 3rd party library.

**Comment by reblace** [comment]
Ok, that's fine I was just curious. That specific package does have a lot of outstanding issues.

**Comment by bodnarbm** [comment]
Regarding angular2-moment, while it only has a single maintainer, I found them to be rather responsive to pull requests (at least in my experience submitting one to them). But now I see an unresponded to PR there that has been open for 20+ days.

**Pull request merged**
