### PR TITLE
Enable code coverage for karma tests.

### PR DESCRIPTION
**Pull request by bodnarbm**

### CODE REVIEW

**Comment by brianghig** [comment]
@ymao1 @reblace @rbutterfield @mheir are you okay with moving the code coverage reports from the `./reports/coverage` directory into the `./reports/coverage/client` and `./reports/coverage/server` directories (in support of this PR adding client-side coverage)?

**Comment by ymao1** [comment]
I have no issue with it. What is the process for these PRs? On our other project, we leave verification instructions (and expected outcome) so that reviewers can verify changes. Maybe that would be a good idea here as well?

**Comment by brianghig** [comment]
Verification Instructions:

1. Run `gulp test-ci`
1. Observe that server-side code coverage report is available in `lcov` and `HTML` formats under `./reports/coverage/server/lcov.info` and `./reports/coverage/server/lcov-report/index.html`, respectively.
1. Similarly, observe that client-side code coverage is available in `lcov` and `HTML` formats at `./reports/coverage/client/lcov.info` and `./reports/coverage/client/lcov-report/index.html`, respectively.

**Review by brianghig — APPROVED** [review]
Looks good. We can tackle Code Climate integration with another PR. Thanks @bodnarbm !

**Review by ymao1 — APPROVED** [review]

**Pull request merged**
