### PR TITLE
Enable Karma Test

### PR DESCRIPTION
**Pull request by bodnarbm**

### CODE REVIEW

**Comment by brianghig** [comment]
@bodnarbm changes look good! Are we waiting on reporting the results of the karma UI tests for a future PR, or should that be available here?

**Comment by bodnarbm** [comment]
@brianghig I updated the PR with two changes.

1. Worked around a bug in karma that results in a significant delay (~30 seconds) in ending the process. The workaround involves calling karma as a child process and waiting for it to end.

2. Added mocha style reporting for the test output.

Not sure if this resolves your prior comment on reporting the results of the karma test.

Eventually we should add code coverage reporting for the karma test also.

**Comment by brianghig** [comment]
@bodnarbm I still need to pull this locally to check it out, but did that second commit make it into this PR? I'm still only seeing the one...

**Comment by bodnarbm** [comment]
@brianghig The second commit was squashed into the first.

**Pull request merged**
